### ISSUE TITLE
run as administrator

### ISSUE THREAD

**Issue by ChandraOrbit** [futurist/runapp#1]
I got a bug,
if the bat file must be run with rus as an administrator then configuration: style: hidden does not work,
is there something wrong with me or is there a solution for: style: hidden to function if run by an administrator?

**Comment by futurist** [comment]
I don't have a windows machine at present, if you can find a solution, then I'm happy to update

**Comment by ChandraOrbit** [comment]
ok, i was wrong
everything is normal,
if the bat file condition is required to run as an administrator, runapp.exe must be run as an administrator so the bat file will automatically follow it.
Thank you in advance
and sorry English is not language.
