### ISSUE TITLE
Add possibility for multi-line comments in .arg files

### ISSUE THREAD

**Issue by daveMueller** [futurist/runapp#3]
Would it be possible to add comments in the .arg file that are excluded when parsing. E.g. a comment starts with ```#This is a comment.```
If you want I can fork it and create the pull request for this.

**Comment by futurist** [comment]
sure, PR is welcome

**Comment by daveMueller** [comment]
Ok there already was the possibilty to add comments in .arg files with ```//``` that I wasn't aware of. I now also added the possibility for multi-line comments with ``` \* *\``` and adapted the documentation in #5 .

**Comment by futurist** [comment]
can you add a simple tests?

**Comment by daveMueller** [comment]
> 
> 
> can you add a simple tests?

Want me to add unit tests? Therefore I would have to refactore a lot of your code. At least make ```Main.cs``` public, introduce an ```IProcessWrapper``` with 2 implementations (one as a fake) and pass ```IProcessWrapper``` as parameter to ```Main.cs``` constructor.

@futurist Do want me to do that? Or do you have a better idea to test this?

**Comment by futurist** [comment]
I see `RegexOptions.Singleline` but the example code shows Multiline mode, I suspect whether the code can work, esp. if it will work as part of a commercial software

**Comment by futurist** [comment]
Or maybe just don't add comment block,  like shell script does. I don't see the necessity till now.

**Comment by daveMueller** [comment]
Yes you are right, there is no necessity for this. I just thought it would be a additional feature that is easy to add to the existing code base. I will close this issue.

Just one more request. Could you create a Release 1.1.2 with the merged Apache 2.0 commit?

**Comment by futurist** [comment]
Here it is:
https://github.com/futurist/runapp/releases/tag/1.1.2

**Comment by daveMueller** [comment]
Thanks a lot. I owe you one.
