### ISSUE TITLE
Release 1.1.2 as executeable

### ISSUE THREAD

**Issue by daveMueller** [futurist/runapp#6]
In the release 1.1.2 there isn't a executeable. In the previous releases there were the source files as assets and a compiled executeable. Could you also add a the executeable to 1.1.2?

The guy in my team who wants to use it isn't a .net programmer and doesn't need (can't compile) the source code.

**Comment by futurist** [comment]
@daveMueller Can you post a compiled binary pack that I can upload to github? since now I have only macOS machine.

**Comment by daveMueller** [comment]
@futurist sure thanks, here are the binaries. 
[runapp.zip](https://github.com/futurist/runapp/files/4604486/runapp.zip)

**Comment by futurist** [comment]
@daveMueller thanks, updated the release file.
